version: '3'
services:

  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '${REDIS_PORT_EXT:-6379}:6379'
    volumes:
      - ./volumes/redis_data:/data

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT_EXT:-5432}:5432'
    volumes:
      - ./volumes/postgres/var/lib/postgresql/data

volumes:
  redis_data:
    driver: local
